pom.xml

[MODRS-3](https://issues.folio.org/browse/MODRS-3) - Remote storages configuration in FOLIO
There are remote-location settings, which is mentioned in "Remote storages configuration in FOLIO" and https://issues.folio.org/browse/UIRS-6. In order not not have unclear policy of eviction for caching of these settings they should be managed by the module itself.
The data should be stored in database and saving in the cache.
Spring Cache - should be used as abstraction for cache.
If there should be more than 1 instance of mod-remote-storage deployed, Hazelcast should be the implementation (as Hazelcast is used on the project) for cache management and eviction.
- Does this PR meet or exceed the expected …

MODRS-3 - Remote storages configuration in FOLIO

---

README.md
descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/rs/controller/ConfigurationsController.java
src/main/java/org/folio/rs/error/DefaultErrorHandler.java
src/main/java/org/folio/rs/error/IdMismatchException.java
src/main/java/org/folio/rs/service/ConfigurationsService.java
src/main/resources/swagger.api/remote-storage.yaml
src/test/java/org/folio/rs/controller/ConfigurationsControllerTest.java

[MODRS-2](https://issues.folio.org/browse/MODRS-2) - Work with remote storage locations
If the location attribute on UI is changed to link the location to the remote one (mark as remote) https://issues.folio.org/browse/UITEN-119, then this information should be stored in database in remote-storage module.
* created endpoint
* updated unit tests
Ideally all …

MODRS-2 - Work with remote storage locations

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/rs/controller/ConfigurationsController.java
src/main/java/org/folio/rs/controller/LocationMappingsController.java
src/main/java/org/folio/rs/controller/TenantController.java
src/main/java/org/folio/rs/domain/entity/Configuration.java
src/main/java/org/folio/rs/domain/entity/ProviderRecord.java
src/main/java/org/folio/rs/service/ProviderService.java
src/main/java/org/folio/rs/service/ProvidersService.java
src/main/resources/swagger.api/remote-storage.yaml
src/main/resources/swagger.api/schemas/provider.json
src/test/java/org/folio/rs/controller/ConfigurationsControllerTest.java

There should single source of truth for remote storage providers, not to duplicate this list on UI.
Added API remote-storage/providers endpoint, that return the list of providers
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …

MODRS-15 - API for list of providers

---

descriptors/ModuleDescriptor-template.json

[MODRS-16](https://issues.folio.org/browse/MODRS-16) - Remote storage backend requests do not work
To prevent remote-storage-module failure due to possible OOM
Increasing of heap size up to 256m.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount …

MODRS-16 - Remote storage backend requests do not work

---

src/main/resources/application.properties

Disable Hibernate show-sql

---

PERSONAL_DATA_DISCLOSURE.md

Place a copy of the personal data disclosure form at the top level of the module github repository to disclose stored types of personal data
- added PERSONAL_DATA_DISCLOSURE.md file
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to …

MODRS-13 - Add personal data disclosure form

---

src/main/java/org/folio/rs/service/AccessionQueueService.java
src/main/java/org/folio/rs/service/SecurityManagerService.java

Improvements for PR [#27](https://github.com/folio-org/mod-remote-storage/pull/27).

MODRS-4 - FOLIO-initiated sending items to the accession queue (sys user permissions improvements)

---

src/main/java/org/folio/rs/service/ConfigurationsService.java
src/main/java/org/folio/rs/service/LocationMappingsService.java
src/main/java/org/folio/rs/service/SecurityManagerService.java

[MODRS-18](https://issues.folio.org/browse/MODRS-18) - Tech Debt: caching for remote storage services
To improve and verify caching for configurations/mappings services.
Cache annotations refactoring …

MODRS-18 - Tech Debt: caching for remote storage services

---

src/main/java/org/folio/rs/controller/TenantController.java

To protect deploying failure (temporary)

FOLIO-2994 - Snapshot env issue (temporary protection)

---

src/main/java/org/folio/rs/service/AccessionQueueService.java

MODRS-18 - Tech debt (improve logging)

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/rs/controller/AccessionController.java
src/main/java/org/folio/rs/controller/RetrieveController.java
src/main/java/org/folio/rs/domain/dto/FilterData.java
src/main/java/org/folio/rs/domain/entity/RetrievalQueueRecord.java
src/main/java/org/folio/rs/error/DefaultErrorHandler.java
src/main/java/org/folio/rs/error/ErrorCode.java
src/main/java/org/folio/rs/mapper/RetrievalQueueMapper.java
src/main/java/org/folio/rs/repository/RetrievalQueueRepository.java
src/main/java/org/folio/rs/service/AccessionQueueService.java
src/main/java/org/folio/rs/service/RetrievalQueueService.java
src/main/resources/db/changelog/changes/initial_schema.sql
src/main/resources/swagger.api/remote-storage.yaml
src/main/resources/swagger.api/schemas/retrievalQueue.json
src/test/java/org/folio/rs/TestSuite.java
src/test/java/org/folio/rs/service/RetrievalQueueServiceTest.java
src/test/resources/ClearTestData.sql

[MODRS-6](https://issues.folio.org/browse/MODRS-6) - Requesting (Retrieval) a Remote Storage Item
API for retrievals should be implemented for interaction with edge-dematic.
GET retrievals, PUT retrievals (to set retrieved/created) endpoints are implemented
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid …

MODRS-6 - Retrieval queue records API

---

src/main/java/org/folio/rs/domain/entity/Configuration.java
src/main/java/org/folio/rs/mapper/ConfigurationsMapper.java
src/main/resources/db/changelog/changes/initial_schema.sql
src/main/resources/swagger.api/schemas/storageConfiguration.json
src/test/java/org/folio/rs/controller/ConfigurationsTest.java

[MODRS-17](https://issues.folio.org/browse/MODRS-17) - Configurations: add credential properties supporting
To allow view of the credential properties one need to introduce new field apiKey in the Configurations schema.
The new apiKey was added to the schema as well as to the entity representation.
configuration schema was changed - optional field was added -> there are no braking changes …

MODRS-17 - Configurations: add credential properties supporting

---

pom.xml

Updating PubSub client to the latest 2.0.0 version

MODRS-21 - mod-remote-storage tenant initialization fails with 500 error

---

pom.xml
src/main/resources/application.yml

[MODRS-22](https://issues.folio.org/browse/MODRS-22) - Health-check for mod-remote-storage
Health check status protocol for mod-remote-storage
Spring actuator enablement
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …

MODRS-22 - Health-check for mod-remote-storage

---

src/main/java/org/folio/rs/service/PubSubService.java
src/main/resources/application.yml

Tech Debt - Application name and version

---

descriptors/ModuleDescriptor-template.json

MODRS-10 - users collection get permission

---

NEWS.md
pom.xml

MODRS-7 - Release 1.0.0

---

README.md
src/main/java/org/folio/rs/controller/ConfigurationsController.java
src/main/java/org/folio/rs/controller/ProviderController.java
src/main/java/org/folio/rs/domain/entity/ProviderRecord.java
src/main/resources/swagger.api/remote-storage.yaml
src/test/java/org/folio/rs/TestSuite.java
src/test/java/org/folio/rs/controller/ConfigurationsTest.java
src/test/java/org/folio/rs/controller/ProviderControllerTest.java

MODRS-23 - Add CaiaSoft Provider to providers list

---

Dockerfile
NEWS.md
pom.xml
run.sh
src/test/resources/mappings/pubsub.json

[MODRS-29](https://issues.folio.org/browse/MODRS-29) - Bugfix release 1.0.1

MODRS-29 - Release-1.0.1

---

src/main/java/org/folio/rs/domain/entity/Configuration.java
src/main/java/org/folio/rs/domain/entity/converters/AccessionWorkflowDetailsConverter.java
src/main/java/org/folio/rs/domain/entity/converters/ReturningWorkflowDetailsConverter.java
src/main/java/org/folio/rs/mapper/ConfigurationsMapper.java
src/main/java/org/folio/rs/service/ConfigurationsService.java
src/main/resources/db/changelog/changes/initial_schema.sql
src/main/resources/swagger.api/schemas/accessionWorkflowDetails.json
src/main/resources/swagger.api/schemas/returningWorkflowDetails.json
src/main/resources/swagger.api/schemas/storageConfiguration.json
src/test/java/org/folio/rs/controller/ConfigurationsTest.java

MODRS - 24 - Extend RS configuration to support accession/return workflows for CaiaSoft

---

descriptors/ModuleDescriptor-template.json

[MODRS-32](https://issues.folio.org/browse/MODRS-32) - Update circulation interface version to 10.0
Update circulation interface version to 10.0
Change circulation interface version in the ModuleDescriptor. …

MODRS-32 - Update circulation interface version to 10.0

---

Jenkinsfile
pom.xml
src/main/java/org/folio/rs/ModRemoteStorageApplication.java
src/main/resources/application.yml
src/test/java/org/folio/rs/TestBase.java

[MODRS-31](https://issues.folio.org/browse/MODRS-31) - Standard health check endpoint
Ensure to add a standard healthcheck endpoint GET /admin/health that returns a 200 if the module is healthy.
* Implemented health check endpoint according to [Back End Module Health Check Protocol](https://wiki.folio.org/display/DD/Back+End+Module+Health+Check+Protocol).
* Updated Jenkinsfile to use new health check endpoint.
* Verified on local testing environment:
`curl --request GET 'http://localhost:9181/admin/health'`
`{"status":"UP"}` …

MODRS-31 - Standard health check endpoint

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/rs/ModRemoteStorageApplication.java
src/main/resources/application.yml
src/test/java/org/folio/rs/TestBase.java

[MODRS-33](https://issues.folio.org/browse/MODRS-33) - Bugfix release 1.0.2

MODRS-33 - Release 1.0.2

---

src/main/java/org/folio/rs/client/AuthnClient.java
src/main/java/org/folio/rs/service/SecurityManagerService.java
src/test/resources/mappings/authn.json

Improve login process for system user.

TD - login process improvement

---

src/main/java/org/folio/rs/controller/TenantController.java

This should fix issue with sample data loading on snapshot ref env:
01:51:20 [] [] [] [] ERROR TenantController     Error loading dematic.json
java.io.FileNotFoundException: class path resource [samples/dematic.json] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/usr/verticles/mod-remote-storage-fat.jar!/BOOT-INF/classes!/samples/dematic.json
at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:217) ~[spring-core-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]

TD - Sample data loading fix issue

---

src/main/resources/samples/dematic.json

[MODRS-28](https://issues.folio.org/browse/MODRS-28) - Make sample data consistent
Sample data for `/remote-storage/configurations` for now has `providerName` field set to wrong value
Corrected sample data …

MODRS-28 - Make sample data consistent

---

src/main/java/org/folio/rs/service/ConfigurationsService.java
src/main/resources/application.yml
src/test/java/org/folio/rs/controller/ConfigurationsTest.java
src/test/java/org/folio/rs/controller/LocationMappingsTest.java

[MODRS-42](https://issues.folio.org/browse/MODRS-42) - Unable to view configuration edits in third pane
Fixing caching mechanism for PUT

MODRS-42 - Unable to view configuration edits in third pane

---

NEWS.md
pom.xml
src/main/java/org/folio/rs/service/ConfigurationsService.java
src/main/resources/application.yml
src/test/java/org/folio/rs/controller/ConfigurationsTest.java
src/test/java/org/folio/rs/controller/LocationMappingsTest.java

Release 1.0.3

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/rs/service/ReturnItemService.java
src/test/java/org/folio/rs/service/ReturnItemServiceTest.java

[MODRS-39](https://issues.folio.org/browse/MODRS-39) - Caiasoft: Returning an Item to remote storage (Duke flow)
Returning items scanned into remote storage when received at remote storage
* updated `remote-storage/return/{remoteStorageConfigurationId}` endpoint
* added error handling
Ideally all of the PRs involved in breaking changes would be merged in …

MODRS-39 - Caiasoft: Returning an Item to remote storage (Duke flow)

---

src/main/java/org/folio/rs/error/AccessionException.java
src/main/java/org/folio/rs/error/DefaultErrorHandler.java
src/main/java/org/folio/rs/error/ErrorCode.java
src/main/java/org/folio/rs/service/AccessionQueueService.java
src/test/java/org/folio/rs/service/AccessionQueueServiceTest.java
src/test/resources/mappings/holdings.json
src/test/resources/mappings/inventory_items.json

[MODRS-52](https://issues.folio.org/browse/MODRS-52) - Accession Flow (Cornell)
Update logic to support accession process for CaiaSoft users (Cornell flow).
* Accession flow updated according to requirements
* Unit tests updated
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …

MODRS-52 - Accession Flow (Cornell)

---

pom.xml

[MODRS-41](https://issues.folio.org/browse/MODRS-41) - Update postgresql to 42.2.18 or spring-boot-starter-parent to 2.3.5.RELEASE
Update spring-boot-starter-parent to 2.3.5.RELEASE
- Changed spring-boot-starter-parent version to 2.3.5.RELEASE
- Changed postgresql version to 42.2.18
- Changed order of lombok and mapstruct-processor in within annotationProcessorPaths
- Error FATAL: unsupported frontend protocol 1234.5680: server supports 2.0 to 3.0 isn't appeared in the logs
- Do …

MODRS-41 - Update postgresql to 42.2.18 or spring-boot-starter-parent to 2.3.5.RELEASE

---

src/main/resources/permissions/system-user-permissions.csv

[MODRS-56](https://issues.folio.org/browse/MODRS-56) - Accession flow (Dematic) doesn't work
To get Accession flow (Dematic) working.
Add required permission to get contributor-type collection from storage. …

MODRS-56 - Added required permission

---

src/main/resources/permissions/system-user-permissions.csv

[MODRS-56](https://issues.folio.org/browse/MODRS-56) - Accession flow (Dematic) doesn't work
To get Accession flow (Dematic) working.
Add required permissions.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially …

MODRS-56-UPD - Changed required permission

---

src/main/java/org/folio/rs/client/LocationClient.java
src/main/java/org/folio/rs/service/LocationMappingsService.java
src/test/resources/mappings/locations.json

[MODRS-67](https://issues.folio.org/browse/MODRS-67) - Improvements for querying mechanism for MappingsController and ExtendedMappingsController
* Impoved GET extended-mappings/locations endpoint
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount …

MODRS-67 - Improvements for querying mechanism for MappingsController and ExtendedMappingsController

---

pom.xml
src/main/resources/db/changelog/changes/initial_schema.sql
src/main/resources/db/changelog/changes/remote_storage_configurations_updateSchema.sql

[MODRS-55](https://issues.folio.org/browse/MODRS-55) - Final verification migration scripts before release
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …

MODRS-55 - database change logs updates

---

NEWS.md
pom.xml

[MODRS-26](https://issues.folio.org/browse/MODRS-26) - MODRS (mod-remote-storage) release

MODRS-26 - Release 1.1.0

---

NEWS.md
pom.xml

[MODRS-69](https://issues.folio.org/browse/MODRS-69) - MODRS (mod-remote-storage) release

MODRS-69 - MODRS (mod-remote-storage) release

---

src/main/java/org/folio/rs/service/AccessionQueueService.java

[MODRS-72](https://issues.folio.org/browse/MODRS-72) - Accession flow for Dematic doesn't work
Logging improvement for bug investigation
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …

MODRS-72 - Accession flow for Dematic doesn't work

---

NEWS.md
pom.xml
src/main/java/org/folio/rs/service/AccessionQueueService.java

[MODRS-73](https://issues.folio.org/browse/MODRS-73) - Release 1.0.5

MODRS-73 - Release 1.0.5

---

src/main/java/org/folio/rs/controller/TenantController.java
src/main/resources/samples/caiaSoft.json
src/main/resources/samples/caia_soft.json
src/main/resources/samples/retrieval_queue_record_for_caia_soft.json
src/test/java/org/folio/rs/controller/ConfigurationsTest.java
src/test/java/org/folio/rs/service/ReturnRetrievalQueueServiceTest.java

[MODRS-63](https://issues.folio.org/browse/MODRS-63) - Create sample data to test caiasoft retrieving jobs
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …

MODRS-63 - Create sample data to test caiasoft retrieving jobs

---

README.md
descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/rs/client/InventoryClient.java
src/main/java/org/folio/rs/controller/ItemsController.java
src/main/java/org/folio/rs/error/DefaultErrorHandler.java
src/main/java/org/folio/rs/error/RequiredValueMissingException.java
src/main/java/org/folio/rs/mapper/ConfigurationsMapper.java
src/main/java/org/folio/rs/service/ConfigurationsService.java
src/main/java/org/folio/rs/service/ItemsService.java
src/main/resources/swagger.api/remote-storage.yaml
src/test/java/org/folio/rs/TestSuite.java
src/test/java/org/folio/rs/controller/ConfigurationsTest.java
src/test/java/org/folio/rs/controller/ItemsTest.java
src/test/resources/mappings/inventory_items.json

[MODRS-74](https://issues.folio.org/browse/MODRS-74) - Implement endpoint to mark item as missing by barcode
Edge modules require ability to mark item as missing by barcode.
* API endpoint /items/barcode/<barcode>/markAsMissing implemented
* unit tests are updated
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid …

MODRS-74 - Implement endpoint to mark item as missing by barcode

---

src/main/java/org/folio/rs/controller/TenantController.java
src/main/java/org/folio/rs/error/TenantNotInitializedException.java
src/main/java/org/folio/rs/integration/KafkaErrorHandler.java
src/main/java/org/folio/rs/integration/KafkaMessageListener.java
src/main/java/org/folio/rs/service/KafkaService.java
src/main/resources/application.yml
src/test/java/org/folio/rs/TestSuite.java
src/test/java/org/folio/rs/error/KafkaErrorHandlerTest.java
src/test/java/org/folio/rs/service/KafkaServiceTest.java

[MODRS-71](https://issues.folio.org/browse/MODRS-71) - Kafka Topics should use ENV variable and tenant id in their naming convention
ENV and tenant id setting should be used in topic naming convention …

MODRS-71 - Kafka Topics should use ENV variable and tenant id in their naming convention

---

NEWS.md
pom.xml
src/main/java/org/folio/rs/controller/TenantController.java
src/main/java/org/folio/rs/error/TenantNotInitializedException.java
src/main/java/org/folio/rs/integration/KafkaErrorHandler.java
src/main/java/org/folio/rs/integration/KafkaMessageListener.java
src/main/java/org/folio/rs/service/KafkaService.java
src/main/resources/application.yml
src/test/java/org/folio/rs/TestSuite.java
src/test/java/org/folio/rs/error/KafkaErrorHandlerTest.java
src/test/java/org/folio/rs/service/KafkaServiceTest.java

[MODRS-75](https://issues.folio.org/browse/MODRS-75) - Bugfix release 1.0.6 (R1)

MODRS-75 - Release-1.0.6

---

descriptors/ModuleDescriptor-template.json

[FOLIO-2994](https://issues.folio.org/browse/FOLIO-2994) - mod-remote-storage unavailable in snapshot environments
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …

FOLIO-2994 - authtoken required

---

NEWS.md
README.md
descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/rs/client/InventoryClient.java
src/main/java/org/folio/rs/controller/ItemsController.java
src/main/java/org/folio/rs/controller/TenantController.java
src/main/java/org/folio/rs/error/DefaultErrorHandler.java
src/main/java/org/folio/rs/error/RequiredValueMissingException.java
src/main/java/org/folio/rs/error/TenantNotInitializedException.java
src/main/java/org/folio/rs/integration/KafkaErrorHandler.java
src/main/java/org/folio/rs/integration/KafkaMessageListener.java
src/main/java/org/folio/rs/mapper/ConfigurationsMapper.java
src/main/java/org/folio/rs/service/AccessionQueueService.java
src/main/java/org/folio/rs/service/ConfigurationsService.java
src/main/java/org/folio/rs/service/ItemsService.java
src/main/java/org/folio/rs/service/KafkaService.java
src/main/resources/application.yml
src/main/resources/swagger.api/remote-storage.yaml
src/main/resources/swagger.api/schemas/storageConfiguration.json
src/test/java/org/folio/rs/TestSuite.java
src/test/java/org/folio/rs/controller/ConfigurationsTest.java
src/test/java/org/folio/rs/controller/ItemsTest.java
src/test/java/org/folio/rs/error/KafkaErrorHandlerTest.java
src/test/java/org/folio/rs/service/KafkaServiceTest.java
src/test/resources/mappings/inventory_items.json

[MODRS-77](https://issues.folio.org/browse/MODRS-77) - MODRS (mod-remote-storage) R2 Bugfix release

MODRS-77 - Release 1.3.0 (R2 2021 Bugfix release)

---

NEWS.md
pom.xml
src/main/java/org/folio/rs/controller/TenantController.java
src/main/java/org/folio/rs/service/SecurityManagerService.java
src/test/java/org/folio/rs/service/SecurityManagerServiceTest.java

[MODRS-83](https://issues.folio.org/browse/MODRS-83) - Bugfix release 1.3.1

MODRS-83 - Release 1.3.1

---

src/main/java/org/folio/rs/controller/TenantController.java
src/test/java/org/folio/rs/TestSuite.java
src/test/java/org/folio/rs/controller/TenantControllerTest.java
src/test/java/org/folio/rs/service/AccessionQueueServiceTest.java
src/test/java/org/folio/rs/service/ReturnRetrievalQueueServiceTest.java

[MODRS-81](https://issues.folio.org/browse/MODRS-81) - Tenant deletion API does not purge database schema
Database schema should be deleted upon tenant deletion (delete tenant with purge=true)
* Updated logic to delete database schema
* Implemented unit test
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid …

MODRS-81 - Tenant deletion API does not purge database schema

---

src/main/java/org/folio/rs/client/InventoryClient.java
src/main/java/org/folio/rs/repository/ExtendedRemoteLocationConfigurationMappingsRepository.java
src/main/java/org/folio/rs/service/CheckInItemService.java
src/main/java/org/folio/rs/service/ReturnItemService.java
src/test/java/org/folio/rs/controller/ReturnItemTest.java
src/test/java/org/folio/rs/service/CheckInItemServiceTest.java
src/test/java/org/folio/rs/service/ReturnItemServiceTest.java
src/test/resources/mappings/inventory_items.json
src/test/resources/mappings/locations.json

[MODRS-89](https://issues.folio.org/browse/MODRS-89) - Juniper Hotfix #3 - Item status becomes ‘In Transit’ when item returns to the remote storage
GVSU production server contains multiple locations with same remote storage configuration. When receiving Item Return message, item status changes from 'Available' to 'In Transit'.
* Fixed logic
* Updated unit tests
- Do PRs exist for these …

MODRS-89 - Juniper Hotfix #3 - Item status becomes ‘In Transit’ when item returns to the remote storage

---

NEWS.md
pom.xml
src/main/java/org/folio/rs/client/InventoryClient.java
src/main/java/org/folio/rs/repository/ExtendedRemoteLocationConfigurationMappingsRepository.java
src/main/java/org/folio/rs/service/CheckInItemService.java
src/main/java/org/folio/rs/service/ReturnItemService.java
src/test/java/org/folio/rs/controller/CheckInRetrieveTest.java
src/test/java/org/folio/rs/controller/ReturnItemTest.java
src/test/java/org/folio/rs/service/CheckInItemServiceTest.java
src/test/java/org/folio/rs/service/ReturnItemServiceTest.java
src/test/resources/mappings/inventory_items.json
src/test/resources/mappings/locations.json

[MODRS-90](https://issues.folio.org/browse/MODRS-90) - MODRS (mod-remote-storage) R2 Hotfix #3 release

MODRS-90 - MODRS (mod-remote-storage) R2 Hotfix #3 release

---

pom.xml
src/main/java/org/folio/rs/client/logger/SensitiveDataProtectionLogger.java
src/test/java/org/folio/rs/service/SecurityManagerServiceTest.java
src/test/resources/mappings/contributor_types.json
src/test/resources/mappings/holdings.json
src/test/resources/mappings/identifier_types.json
src/test/resources/mappings/instance_collection.json
src/test/resources/mappings/inventory_items.json
src/test/resources/mappings/users.json

[MODRS-85](https://issues.folio.org/browse/MODRS-85) - mod-remote-storage: folio-spring-base v2 update
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …

MODRS-85 - mod-remote-storage: folio-spring-base v2 update

---

NEWS.md
pom.xml

[MODRS-60](https://issues.folio.org/browse/MODRS-60) - MODRS (mod-remote-storage) release …

MODRS-60 - Release 1.4.0

---

NEWS.md
pom.xml
src/main/java/org/folio/rs/service/AccessionQueueService.java
src/test/java/org/folio/rs/service/AccessionQueueServiceTest.java

[MODRS-97](https://issues.folio.org/browse/MODRS-97) - Bugfest release 1.4.1

MODRS-97 - Bugfest release 1.4.1

---

pom.xml

[MODRS-103](https://issues.folio.org/browse/MODRS-103) - Kiwi R3 2021 - Log4j vulnerability verification and correction

MODRS-103 - Kiwi R3 2021 - Log4j vulnerability verification and correction

---

NEWS.md
pom.xml

[MODRS-108](https://issues.folio.org/browse/MODRS-108) - MODRS (mod-remote-storage) Kiwi Bugfix release

MODRS-108 - Release 1.4.2

---

NEWS.md
pom.xml

[MODRS-107](https://issues.folio.org/browse/MODRS-107) - MODRS (mod-remote-storage) Juniper Hotfix release

MODRS-107 - Release 1.3.4

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/rs/client/CirculationClient.java
src/test/resources/mappings/circulation.json

Adapt the module to changed interface of mod-circulation from v12.0 to v13.0
- Adapt ModuleDescriptor-template to circulation v13.0;
- Adapt CirculationClient to new endpoint;
- Tests fix;
https://issues.folio.org/browse/MODRS-115

MODRS-115 Support circulation interface v13

---

pom.xml
src/main/java/org/folio/rs/integration/KafkaMessageListener.java
src/test/java/org/folio/rs/TestSuite.java
src/test/java/org/folio/rs/service/KafkaListenerTest.java

[MODRS-114](https://issues.folio.org/browse/MODRS-114) - mod-remote-storage fails to recover from invalid token
Re-authorisation mechanism in mod-remote-storage: when Feign-client get error 401, it should try to re-athentificate the user.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …

MODRS-114 - mod-remote-storage fails to recover from invalid token

---

descriptors/ModuleDescriptor-template.json

[MODRS-104](https://issues.folio.org/browse/MODRS-104) - Accessioning holdings & items to remote storage fails when no order record is present
GVSU is unable to accession items into newly created holdings when the items do not have order records associated with them
* Fixed permissions
Ideally all of the PRs involved in breaking changes would be merged in …

MODRS-104 - Accessioning holdings & items to remote storage fails when no order record is present

---

NEWS.md
pom.xml

[MODRS-112](https://issues.folio.org/browse/MODRS-112) - Release 1.5.0

MODRS-112 - Release 1.5.0

---

NEWS.md

NEWS.md updating to include missing stories
Update NEWS.md to include MODRS-114 in the list
Update NEWS.md
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …

NEWS.md updating to include missing stories

---

pom.xml
src/main/java/org/folio/rs/controller/TenantController.java

[MODRS-118](url) - mod-remote-storage: folio-spring-base update
Upgrade folio-spring-base to 4.1.0
Upgrade spring-boot-starter-parent to 2.7.*
Change pom.xml.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially …

MODRS-118 - mod-remote-storage: folio-spring-base update

---

pom.xml

[MODRS-124](https://issues.folio.org/browse/MODRS-124) - Remove org.json:json, license is not open source
Remove org.json:json dependency: https://github.com/folio-org/mod-remote-storage/blob/v1.5.0/pom.xml#L106-L110
* Removed dependency
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …

MODRS-124 - Remove org.json:json, license is not open source

---

src/main/java/org/folio/rs/service/AccessionQueueService.java
src/test/java/org/folio/rs/TestBase.java
src/test/java/org/folio/rs/controller/TenantControllerTest.java
src/test/java/org/folio/rs/service/AccessionQueueServiceTest.java

[MODRS-130](https://issues.folio.org/browse/MODRS-130)  - Close FolioExecutionContext if it is opened
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …

MODRS-130 - Close FolioExecutionContext if it is opened

---

NEWS.md
pom.xml

[MODRS-117](https://issues.folio.org/browse/MODRS-117) - MODRS (mod-remote-storage) release

MODRS-117 - Release 1.6.0

---

src/main/java/org/folio/rs/domain/entity/ProviderRecord.java

[MODRS-134](https://issues.folio.org/browse/MODRS-134) - Update Dematic names in remote storage configuration settings
Update Dematic remote storage names to reflect connection paths, not StagingDirector or EMS
Change ProviderRecord.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …

MODRS-134 - Update Dematic names in remote storage configuration settings

---

pom.xml

[MODRS-138](https://issues.folio.org/browse/MODRS-138) - mod-remote-storage: spring upgrade …

MODRS-138 - mod-remote-storage: spring upgrade

---

NEWS.md
pom.xml

[MODRS-128](https://issues.folio.org/browse/MODRS-128) - [Release 1.7.0](mod-remote-storage: spring upgrade)

MODRS-128 - Release 1.7.0

---

NEWS.md
pom.xml

[MODRS-144](https://issues.folio.org/browse/MODRS-144) - Release 1.7.1

MODRS-144 - Release 1.7.1

---

src/main/java/org/folio/rs/service/AccessionQueueService.java
src/main/java/org/folio/rs/service/CheckInItemService.java
src/main/java/org/folio/rs/service/ItemsService.java
src/main/java/org/folio/rs/service/LocationMappingsService.java
src/main/java/org/folio/rs/service/ReturnItemService.java
src/main/java/org/folio/rs/service/ReturnRetrievalQueueService.java

https://issues.folio.org/browse/MODRS-119
1. Logging improvement 
1. info and debug log added as per need

[MODRS-119] logging improvement

---

pom.xml

https://issues.folio.org/browse/MODRS-156
1. Folio spring base version updated to pass build.
1. pom.xml updated to pass build

[MODRS-156] 1. dependency updated

---

NEWS.md
pom.xml

MODRS-152 (https://issues.folio.org/browse/MODRS-152)
1. Release for Orchid

Tmp release 2.0.0

---

NEWS.md
pom.xml
src/main/resources/application.yml

For Orchid 2.0.1 release for https://issues.folio.org/browse/BF-459

Orchid 2.0.1 release

---

NEWS.md
pom.xml

To upgrade the snapshot version in pom and news.md file for master.

[MODRS-159] - Post 2.0.1 release update to master.

---

NEWS.md
pom.xml

To release 1.7.2

---

NEWS.md
pom.xml

To release 2.0.3

---

pom.xml

to upgrade pom version after 2.0.3 release

Upgrade pom version

---

descriptors/ModuleDescriptor-template.json

Resolves - [MODRS-178](https://issues.folio.org/browse/MODRS-178)
The Purpose of this PR is to Add Missing Permission which is causing the internal server error.
Added Missing Permission in module descriptor.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication …

MODRS-178 Missing Permission to Inventory

---

pom.xml

Upgrade folio-spring dependencies in pom version.
Updated the version.
While it's helpful …

[MODRS-182] - upgrade versions for folio-spring dependencies.

---

pom.xml
src/main/resources/db/changelog/changes/accession_update_schema.xml
src/main/resources/db/changelog/changes/add_item_notes_table.xml
src/main/resources/db/changelog/changes/initial_schema.xml
src/main/resources/db/changelog/changes/location_mappings_update_schema.xml
src/main/resources/db/changelog/changes/location_mappings_update_schema_tech_debt.xml
src/main/resources/db/changelog/changes/remote_storage_configurations_updateSchema.xml
src/main/resources/db/changelog/changes/retrieval_update_schema.xml

Updating spring boot starter dependency version to 3.1.4
After updating spring boot starter version to 3.1.4, test cases are getting failed because of liquibase exception. So in order to fix it, changed the sqlfile path inside all the schema.xml file.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …

MODRS-183 Updating spring boot starter dependency version to 3.1.4

---

NEWS.md
pom.xml

To release 3.0.1

---

NEWS.md
pom.xml

After Tmp release 3.0.1 update pom version

---

pom.xml

Bump module version after v3.1.0 was released
- `3.0.2-SNAPSHOT` -> `3.2.0-SNAPSHOT`

MODRS-193: bump module version to 3.2.0-SNAPSHOT

---

pom.xml
src/main/java/org/folio/rs/config/KafkaConfiguration.java
src/main/resources/swagger.api/schemas/instance.json
src/main/resources/swagger.api/schemas/instanceContributors.json
src/main/resources/swagger.api/schemas/instanceIdentifiers.json
src/main/resources/swagger.api/schemas/instancePublication.json
src/main/resources/swagger.api/schemas/item.json
src/main/resources/swagger.api/schemas/itemContributorNames.json

The purpose of the PR is to implement MODRS-194
After Openapi version upgradation to 7.3.0, it generates instanceidentifiersinner class instead of instanceindentifiers class. It looks like the entire identifier object is declared inside instance.json file so it is creating such kind of class. This is breaking in the existing class which are refering instanceidentifiers. So instanceIdentifiers.json file is created and referred from instance.json file. same approach followed for instanceContributors.json, instancePublication.json and itemContributorNames.json as well. 
We did the fix only for the classes which is breaking the code 
- Does …

MODRS-194 Updating dependencies for Quesnelia

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

[MODRS-196]-Q release 3.2.0

---

descriptors/ModuleDescriptor-template.json

To upgrade the API version for holdings-storage. …

[MODRS-200] - API version update

---

descriptors/ModuleDescriptor-template.json

https://folio-org.atlassian.net/browse/MODRS-206
Added interface **item-note-types** with version 1.0
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …

MODRS-206 Missing required interfaces in Module Descriptor

---

descriptors/ModuleDescriptor-template.json

Upgrade inventory version to 14.0
While it's helpful for reviewers to help identify …

[MODRS-210] - inventory API version update

---

descriptors/ModuleDescriptor-template.json
pom.xml

Fixed permission names as per MODRS-205
Related PRS - https://github.com/folio-org/edge-dematic/pull/102
https://github.com/folio-org/mod-pubsub/pull/271
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as …

[MODRS-205] - Permission changes in MD file

---

pom.xml

https://folio-org.atlassian.net/browse/MODRS-211 …

MODRS-211: upgraded folio-spring-base.version from 8.1.0 to 8.2.0

---

descriptors/ModuleDescriptor-template.json
pom.xml

Revert the permissions for MODPUBSUB-301

---

pom.xml
src/main/resources/hazelcast.yaml

hazelcast-fix-custom-cluster-name: custom hazelcast cluster-name is set

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

https://folio-org.atlassian.net/browse/MODRS-214 …

MODRS-214: Ramsons release

---

descriptors/ModuleDescriptor-template.json
pom.xml

[MODRS-216] - Add permissions in pubsub module for MD file changes in Eureka

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

Post release 3.3.1

---

descriptors/ModuleDescriptor-template.json

https://folio-org.atlassian.net/browse/CIRC-2139
https://folio-org.atlassian.net/browse/MODRS-219
- update permission
it will be merged after pr https://github.com/folio-org/mod-circulation/pull/1508

[MODRS-219] - update permissions for mod-patron

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

Resolves: [MODRS-219](https://folio-org.atlassian.net/browse/MODRS-219)

MODRS-219 Release 3.3.2

---

descriptors/ModuleDescriptor-template.json

https://folio-org.atlassian.net/browse/MODRS-225 …

MODRS-225: upgraded interface version for service-points from 3.3 to 3.4

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

https://folio-org.atlassian.net/browse/MODRS-225 …

To release v3.3.4

---

.github/workflows/postgres.yml
Dockerfile
Jenkinsfile
pom.xml
src/test/java/org/folio/rs/client/InventoryClientTest.java
src/test/java/org/folio/rs/client/UsersClientTest.java
src/test/java/org/folio/rs/controller/TenantControllerTest.java
src/test/java/org/folio/rs/service/KafkaServiceTest.java
src/test/resources/mappings/users.json

FOLIO-4216 - Java and spring boot version upgrade

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

https://folio-org.atlassian.net/browse/MODRS-230 …

Sunflower release 3.4.0

---

NEWS.md
pom.xml

https://folio-org.atlassian.net/browse/MODRS-234
https://folio-org.atlassian.net/browse/MODRS-234
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …

To release 3.4.1

---

NEWS.md
pom.xml
src/main/resources/db/changelog/changelog-master.xml
src/main/resources/db/changelog/changes/add_item_notes_item_id_idx.sql
src/main/resources/db/changelog/changes/add_item_notes_item_id_idx.xml

https://folio-org.atlassian.net/browse/MODRS-235 …

Sunflower Bugfix R1 release 3.4.2

---

NEWS.md

To Sync NEWS.md file from long live branch to master branch
While it's helpful for reviewers …

Post release 3.4.2

---

NEWS.md
pom.xml
src/main/resources/application.yml

Sunflower Bug fix R1 2025
https://folio-org.atlassian.net/browse/MODRS-237
While it's …

Sunflower release 3.4.3

---

NEWS.md

Post release 3.4.3

---

descriptors/ModuleDescriptor-template.json
src/main/resources/permissions/system-user-permissions.csv

Jira Issue: https://folio-org.atlassian.net/browse/MODRS-242
Fix the missing permission issue for a system user
- Adds a missing `inventory.instances.item.get` for system user
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …

MODRS-242: Add missing permission to system user

---

.github/PULL_REQUEST_TEMPLATE.md
.github/dependabot.yml
CODEOWNERS

- to have in place the process for automation of the updates of dependent modules
- to have standardized approach for all the Pull Requests created for the modules of volaris team
- for codeowners been automatically tagged in PRs
- add `dependabot.yml` config file
- add `PULL_REQUEST_TEMPLATE.md` file
- add `CODEOWNERS` file
[MODRS-241](https://folio-org.atlassian.net/browse/MODRS-241)
- …

MODRS-241: Add config file for dependabot and template for pull request

---

NEWS.md
descriptors/ModuleDescriptor-template.json

Bump version of `item-storage` as it has breaking change
bump dependency for api `item-storage`
[MODRS-243](https://folio-org.atlassian.net/browse/MODRS-243)

MODRS-243: item storage api version update
